# Generated by Django 5.1 on 2024-08-30 10:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstitle', models.CharField(max_length=100)),
                ('newsdes', tinymce.models.HTMLField()),
            ],
        ),
    ]
