# Generated by Django 5.1 on 2024-08-30 19:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsslug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='newstitle', unique=True),
        ),
    ]
