# Generated by Django 5.1 on 2024-10-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbenter', '0004_csvrecord_delete_dataentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='CSVRecord',
        ),
    ]
